apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-shortener-backend
  labels:
    app: link-shortener-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-shortener-backend
  template:
    metadata:
      labels:
        app: link-shortener-backend
    spec:
      containers:
      - name: backend
        image: link-shortener-backend
        ports:
        - containerPort: 8080 # .NET 8.0 varsayılan olarak 8080 portunu dinler, hazır buradayken bunu da güncelleyelim.