apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkshortener.fullname" . }}-secrets
  namespace: "linkshortener-{{.Values.environment}}"
type: Opaque
data:
  ConnectionStrings__PostgreSQL: SG9zdD1sb2NhbC1kb2NrZXItaG9zdDtQb3J0PTU0MzI7RGF0YWJhc2U9bGlua3Nob3J0ZW5lcl9kYjtVc2VybmFtZT1hZG1pbjtQYXNzd29yZD1zZWNyZXRwYXNzd29yZA==
  ConnectionStrings__Redis: bG9jYWwtZG9ja2VyLWhvc3Q6NjM3OSxhYm9ydENvbm5lY3Q9ZmFsc2U=
  JwtSettings__Secret: QnUgQ29rX0dpemxpX1ZlX0d1dmVubGlfQmlyX01pbl8zMl9LYXJha3RlcmxpX0FuYWh0YXJkZXIyMDI2
  RabbitMQ__Username: Z3Vlc3Q=
  RabbitMQ__Password: Z3Vlc3Q=
