apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkshortener.fullname" . }}-svc
  namespace: "linkshortener-{{.Values.environment}}"
  labels:
    {{- include "linkshortener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "linkshortener.name" . }}
    env: {{ .Values.environment }}