environment: dev
dotnetEnv: Development
isWorkerEnabled: true
replicaCount: 1

image:
  repository: mcysrdckr/link_shortener
  tag: d814c57e7704aff646243b269fbccda00e389454 # GitHub Actions buradaki tag'i v1.2.3 olarak güncelleyecek
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

# TEST ortamında PostSync k6 Yük Testi AKTİF
k6Test:
  enabled: true
  scriptConfigMapName: k6-test-script-configmap
  shortCode: "iZr6N9c"
  script: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      vus: 5,
      duration: '10s',
    };

    export default function () {
      // Kubernetes içi Service üzerinden veya Ingress host adresi üzerinden erişim
      const res = http.get('http://{{ include "linkshortener.fullname" . }}-svc/api/health');
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
      sleep(1);
    }

resources:
  requests:
    cpu: 100m
    memory: 128Mi