environment: test
dotnetEnv: Test
isWorkerEnabled: true
replicaCount: 2

image:
  repository: mcysrdckr/link_shortener
  tag: d814c57e7704aff646243b269fbccda00e389454 # GitHub Actions buradaki tag'i v1.2.3 olarak güncelleyecek
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

# TEST ortamında PostSync k6 Yük Testi AKTİF
k6Test:
  enabled: true
  scriptConfigMapName: k6-test-script-configmap

resources:
  requests:
    cpu: 100m
    memory: 128Mi