environment: test
dotnetEnv: Test
isWorkerEnabled: true
replicaCount: 2
image:
  repository: mcysrdckr/link_shortener
  tag: 75f03d6c2c81e67a179b9e3b2825caef56e668c7 # GitHub Actions buradaki tag'i v1.2.3 olarak güncelleyecek
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
# TEST ortamında PostSync k6 Yük Testi AKTİF
k6Test:
  enabled: true
  scriptConfigMapName: k6-test-script-configmap
  shortCode: "iZr6N9c"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
