environment: test
dotnetEnv: Test
isWorkerEnabled: true
replicaCount: 2
image:
  repository: mcysrdckr/link_shortener
  tag: 10f92e691aafae869357608aec05a806d3b12c74 # GitHub Actions buradaki tag'i v1.2.3 olarak güncelleyecek
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
# TEST ortamında PostSync k6 Yük Testi AKTİF
k6Test:
  enabled: true
  scriptConfigMapName: k6-test-script-configmap
  shortCode: "iZr6N9c"
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m # 1 tam çekirdeğe kadar burst yapabilsin
    memory: 512Mi
