apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - link-shortener-namespace.yaml
  - link-shortener-secrets.yaml
  - link-shortener-config.yaml
  - link-shortener-deployment.yaml
  - link-shortener-service.yaml
  - link-shortener-ingress.yaml
  - dynamodb-service.yaml

images:
  - name: link-shortener-backend
    newName: mcysrdckr/link_shortener
    newTag: ee66c6e131704d1cdac7a317dd42228f74082d3a
