apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: link-shortener
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.57 # Güncel kararlı all-in-one imajı
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true" # OpenTelemetry desteğini açıyoruz
        ports:
        - containerPort: 16686 # Jaeger UI (Arayüz portu)
        - containerPort: 4317  # OTLP gRPC Alıcı portu (Biz burayı kullanacağız)
        - containerPort: 4318  # OTLP HTTP Alıcı portu
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: link-shortener
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  type: ClusterIP