apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: link-shortener
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.95.0
        args: ["--config=/etc/otelcol/config.yaml"]
        ports:
        - containerPort: 4317 # OTLP gRPC portu
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otelcol
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: link-shortener
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      batch:
    exporters:
      otlp: # Traceleri Jaeger'a gönderir
        endpoint: "jaeger-service:4317"
        tls:
          insecure: true
      prometheus: # Metrikleri Prometheus için dışarı açar
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: link-shortener
spec:
  selector:
    app: otel-collector
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
  - name: metrics-scrape
    port: 8889
    targetPort: 8889
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: link-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.51.0
        args: ["--config.file=/etc/prometheus/prometheus.yml"]
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: link-shortener
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          # Prometheus artık deneysel flag olmadan, doğrudan Collector'ın 8889 portunu kazıyor!
          - targets: ['otel-collector-service:8889']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: link-shortener
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090