apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - link-shortener-namespace.yaml
  - link-shortener-secrets.yaml
  - link-shortener-config.yaml
  - link-shortener-deployment.yaml
  - link-shortener-consumer-deployment.yaml
  - link-shortener-service.yaml
  - link-shortener-ingress.yaml
  - dynamodb-service.yaml

images:
  - name: link-shortener-backend
    newName: mcysrdckr/link_shortener
    newTag: 47d156eb6b9d8a4106d5763cbdff846e4e1d3abd