apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - link-shortener-namespace.yaml
  - link-shortener-secrets.yaml
  - link-shortener-config.yaml
  - link-shortener-deployment.yaml
  - link-shortener-consumer-deployment.yaml
  - link-shortener-service.yaml
  - link-shortener-ingress.yaml
  - dynamodb-service.yaml
  - link-shortener-external-service.yaml

images:
  - name: link-shortener-backend
    newName: mcysrdckr/link_shortener
    newTag: 4698f139585e7d3426dbec5f8d1a529da6102672