apiVersion: v1
kind: Secret
metadata:
  name: link-shortener-secrets
  namespace: link-shortener
type: Opaque
data:
  ConnectionStrings__PostgreSQL: SG9zdD1ob3N0LmRvY2tlci5pbnRlcm5hbDtQb3J0PTU0MzI7RGF0YWJhc2U9bGlua3Nob3J0ZW5lcl9kYjtVc2VybmFtZT1hZG1pbjtQYXNzd29yZD1zZWNyZXRwYXNzd29yZA==
  ConnectionStrings__Redis: aG9zdC5kb2NrZXIuaW50ZXJuYWw6NjM3OSxjb25uZWN0VGltZW91dD0yMDAwLHN5bmNUaW1lb3V0PTMwMA==
  JwtSettings__Secret: QnUgQ29rX0dpemxpX1ZlX0d1dmVubGlfQmlyX01pbl8zMl9LYXJha3RlcmxpX0FuYWh0YXJkZXIyMDI2
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=

