apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: link-shortener-backend # base'deki imaj adı ile BİREBİR aynı olmalı
    newName: 189056847276.dkr.ecr.eu-central-1.amazonaws.com/link-shortener-backend
    newTag: bb5dac86c38200f1777a31a7810c1e2d78bfdad1
