apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: nginx
    newName: 189056847276.dkr.ecr.eu-central-1.amazonaws.com/link-shortener-backend
    newTag: e5d623bd7e5e48f2451cd52b74ec3d15f082e5fd