apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: link-shortener-backend # base'deki imaj adı ile BİREBİR aynı olmalı
    newName: <AWS_ACCOUNT_ID>.dkr.ecr.eu-central-1.amazonaws.com/link-shortener-backend # Başlangıç için AWS ECR URI'niz
    newTag: latest # GitHub Actions burayı dinamik olarak Commit SHA yapacak
